tasks:
  - id: "werewolf"
    type: "werewolf"
    description: "Annotate werewolf game audio"
    data_file: "data/werewolf.jsonl"
    instructions: |
      **Werewolf Instructions**
      
      1. Listen to the audio.
      2. Rename speakers if needed.
      3. Vote for the most likely werewolf.
    audio: true
    audio_path_prefix: "https://firebasestorage.googleapis.com/v0/b/hai-gcp-accents-dialects.appspot.com/o/audio%2Fwerewolf%2F"
    transcript: true
    display_fields:
      - filename
    choice_field: "PlayerNames"
    extra_choices:
      - "No werewolves"
    combined_roles_fields:
      - startRoles
      - endRoles
    default_roles:
      - werewolf
      - villager
      - robber
      - troublemaker

  - id: "pronunciation_oed"
    type: "pronunciation"
    description: "Record your pronunciation from OED entry"
    data_file: "data/pronunciation.jsonl"
    instructions: |
      **Pronunciation OED Instructions**
      
      Your task is to record your pronunciation of each word based on the OED (Oxford English Dictionary) entry.
      The OED entry shows how the word is pronounced using a special spelling system that represents the sounds.
      
      1. Read the OED entry carefully to understand the correct pronunciation.
      2. Click "Start Recording" to record your pronunciation of the word.
      3. Click "Stop Recording" when you're done.
      4. Listen to your recording to ensure your pronunciation is clear and accurate.
      5. If needed, click "Re-Record" to try again.
      6. Use the Previous/Next buttons to navigate between words.
      
      Focus on pronouncing the word exactly as indicated in the OED entry.
    audio: false
    audio_path_prefix: "https://firebasestorage.googleapis.com/v0/b/hai-gcp-accents-dialects.appspot.com/o/audio%2Fpronunciation%2F"
    recording: true
    showOED: true
    showAudio: false
    display_fields:
      - filename
      - word
      - OED
      - region

  - id: "pronunciation_echo"
    type: "pronunciation"
    description: "Record your pronunciation from reference audio"
    data_file: "data/pronunciation.jsonl"
    instructions: |
      **Pronunciation Echo Instructions**
      
      Your task is to record your pronunciation of each word by matching the reference audio.
      
      1. Click play to listen to the reference pronunciation.
      2. Click "Start Recording" to record your pronunciation of the word.
      3. Click "Stop Recording" when you're done.
      4. Listen to your recording to ensure your pronunciation matches the reference.
      5. If needed, click "Re-Record" to try again.
      6. Use the Previous/Next buttons to navigate between words.
      
      Focus on matching the pronunciation in the reference audio as closely as possible.
    audio: true
    audio_path_prefix: "https://firebasestorage.googleapis.com/v0/b/hai-gcp-accents-dialects.appspot.com/o/audio%2Fpronunciation%2F"
    recording: true
    showOED: false
    showAudio: true
    display_fields:
      - filename
      - word
      - region

  - id: "jeopardy"
    type: "jeopardy"
    description: "Click play to hear the question, then buzz in when you know the answer (or make your best guess)"
    data_file: "data/jeopardy.jsonl"
    instructions: |
      **Jeopardy Instructions**
      
      1. Click play to listen to the question audio
      2. When you know the answer, click the "Buzz In!" button
      3. Your answer will be recorded automatically
      4. You can play back your recording
      5. If you experience audio issues, you can report them and re-record
      6. Your answer will be submitted automatically after recording
      7. If you don't know the answer, still buzz in and say "I don't know" or "I'm not sure" or make your best guess to move on
    audio: true
    audio_path_prefix: "https://firebasestorage.googleapis.com/v0/b/hai-gcp-accents-dialects.appspot.com/o/audio%2Fjeopardy%2F"
    timing: true
    display_fields:
      - filename
    meta_fields:
      - answer

  - id: "emotion"
    type: "emotion"
    description: "Annotate speaker emotion"
    data_file: "data/emotion.jsonl"
    audio: true
    audio_path_prefix: "https://firebasestorage.googleapis.com/v0/b/hai-gcp-accents-dialects.appspot.com/o/audio%2Femotion%2F"
    display_fields:
      - filename
      - sentence
    choice_field: "expected_emotions"